# Generated by Django 4.2.1 on 2023-05-24 07:32

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефону')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('сity', models.CharField(max_length=30, verbose_name='Ваше місто')),
                ('delivery_way', models.CharField(choices=[('SP', 'Store pickup'), ('TD', 'Targeted delivery'), ('MP', 'Mobile pickup'), ('PD', 'Postal delivery')], max_length=10, verbose_name='Спосіб доставки')),
                ('payment', models.CharField(choices=[('PR', 'payment on receipt'), ('СD', 'Card'), ('SC', 'Social Card'), ('NC', 'Non-cash'), ('IN', 'Installments')], max_length=10)),
                ('data', models.DateField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='orders', to='product.product', verbose_name='Назва товару')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET('видалений користувач'), to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
