# Generated by Django 4.2.1 on 2023-05-20 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефону')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('сity', models.CharField(max_length=30, verbose_name='Ваше місто')),
                ('delivery_way', models.CharField(choices=[('SP', 'Store pickup'), ('TD', 'Targeted delivery'), ('MP', 'Mobile pickup'), ('PD', 'Postal delivery')], max_length=10, verbose_name='Спосіб доставки')),
                ('payment', models.CharField(choices=[('PR', 'payment on receipt'), ('СD', 'Card'), ('SC', 'Social Card'), ('NC', 'Non-cash'), ('IN', 'Installments')], max_length=10)),
            ],
        ),
    ]
