# Generated by Django 4.2.1 on 2023-05-20 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET('видалений користувач'), to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
