# Generated by Django 4.2.1 on 2023-05-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buyer', models.BooleanField(default=False)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('pros', models.TextField(blank=True, max_length=360, null=True)),
                ('cons', models.TextField(blank=True, max_length=360, null=True)),
                ('upvote', models.PositiveIntegerField()),
                ('downvote', models.PositiveIntegerField()),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedbacks.feedback')),
                ('user', models.ForeignKey(default='AnonymousUser', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedbacks',
            },
        ),
    ]
