# Generated by Django 4.2.1 on 2023-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='upvote',
        ),
        migrations.AddField(
            model_name='feedback',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
