# Generated by Django 4.2.1 on 2023-05-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_alter_feedback_comment_feedbackcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
    ]
