# Generated by Django 4.2.1 on 2023-05-26 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_url_img_alter_brand_slug_alter_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0007_feedback_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcomment',
            options={'verbose_name_plural': 'feedback comments'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(auto_created='feedbacks', default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
